!Config
announcables:
- '&7[&b*&7] Welcome to 1337Clan'
- '&7[&b*&7] We are currently in the alpha stages of our new chat system'
- '&7[&b*&7] Please report any issues to a staff member'
- '&7[&b*&7] Thank you for playing!'
- '&7[&b*&7] Don''t forget to vote for us'
database: chat
interval: 600000
password: '1337h4x'
url: 'dev.1337clan.com'
user: minecraft
